language: node_js
node_js: '4'
sudo: false
cache:
  directories:
  - ./node_modules
env:
  global:
  - _STEP_DELAY_MS=1500
before_install:
- if [[ "$(npm --version)" =~ ^1\..+ ]]; then npm install -g npm@2; fi
script:
- npm run lint
- npm run coverage
- npm run feature
after_script:
- if [[ -e ./coverage/lcov.info ]]; then npm run coveralls; else false; fi
notifications:
  email: false
